Repository technocake/goto, pull requests merged in 2019-07, with the labels that each got.

#73 Refactor each command into separate modules
  .circleci/config.yml
  .editorconfig
  goto/commands/__init__.py
  goto/commands/add.py
  goto/commands/cd.py
  goto/commands/copy.py
  goto/commands/default.py
  goto/commands/intellij.py
  goto/commands/list.py
  goto/commands/open.py
  goto/commands/rm.py
  goto/commands/show.py
  goto/commands/subl.py
  goto/commands/update.py
  goto/commands/usage.py
  goto/commands/vscode.py
  goto/gotomagic/handlers.py
  goto/gotomagic/magic.py
  goto/gotomagic/text.py
  goto/gotomagic/text/__init__.py
  goto/gotomagic/text/error.py
  goto/gotomagic/text/text.py
  goto/gotomagic/text/warning.py
  goto/gotomagic/utils.py
  goto/tests/test_end_to_end.sh
  goto/tests/test_gotomagic.py
  goto/tests/test_text.py
  goto/the_real_goto.py
  tox.ini
Labels: refactor

#78 Release/1.5.0
  .circleci/config.yml
  .editorconfig
  bin/_gotoutils
  bin/goto
  bin/install_goto
  bin/project
  bin/start_goto
  goto/commands/__init__.py
  goto/commands/add.py
  goto/commands/cd.py
  goto/commands/copy.py
  goto/commands/default.py
  goto/commands/intellij.py
  goto/commands/list.py
  goto/commands/open.py
  goto/commands/rm.py
  goto/commands/show.py
  goto/commands/subl.py
  goto/commands/update.py
  goto/commands/usage.py
  goto/commands/vscode.py
  goto/gotomagic/git.py
  goto/gotomagic/handlers.py
  goto/gotomagic/magic.py
  goto/gotomagic/text.py
  goto/gotomagic/text/__init__.py
  goto/gotomagic/text/error.py
  goto/gotomagic/text/text.py
  goto/gotomagic/text/warning.py
  goto/gotomagic/utils.py
  goto/tests/test_end_to_end.sh
  goto/tests/test_gotomagic.py
  goto/tests/test_text.py
  goto/the_real_goto.py
  requirements.txt
  requirements_dev.txt
  setup.py
  tox.ini
Labels: enhancement, feature, refactor, zsh

#96 Feature/warn user about ampersand
  bin/goto
  goto/gotomagic/text/warning.py
  goto/gotomagic/utils.py
  goto/tests/test_end_to_end.sh
  goto/the_real_goto.py
Labels: feature, security, test on all platforms (win|linux|osx)

#89 Add goto rename <from> <to>
  .gitignore
  README.md
  bin/start_goto
  goto.sublime-project
  goto/commands/__init__.py
  goto/commands/rename.py
  goto/commands/usage.py
  goto/gotomagic/magic.py
  goto/gotomagic/text/warning.py
  goto/tests/test_end_to_end.sh
  goto/the_real_goto.py
Labels: feature

#107 Cleanup
  MANIFEST.in
  Makefile
  README.md
  bin/goto
  bin/project
  goto/commands/add.py
  goto/commands/copy.py
  goto/commands/intellij.py
  goto/commands/list.py
  goto/commands/open.py
  goto/commands/rename.py
  goto/commands/rm.py
  goto/commands/show.py
  goto/commands/subl.py
  goto/commands/usage.py
  goto/commands/vscode.py
  goto/gotomagic/git.py
  goto/gotomagic/magic.py
  goto/gotomagic/text/__init__.py
  goto/gotomagic/text/error.py
  goto/gotomagic/text/text.py
  goto/gotomagic/text/warning.py
  goto/gotomagic/utils.py
  goto/settings.py
  goto/tests/test_gotomagic.py
  goto/the_real_goto.py
  requirements.txt
  requirements_dev.txt
  setup.py
  test_end_to_end.sh
  tox.ini
Labels: enhancement

#112 add migration automagic and detection for unmigrated data
  bin/_gotoutils
  bin/goto
  bin/project
  goto/__init__.py
  goto/commands/__init__.py
  goto/commands/migrate.py
  goto/gotomagic/text/text.py
  goto/gotomagic/text/warning.py
  goto/gotomagic/utils.py
  goto/the_real_goto.py
  test_end_to_end.sh
Labels: critical, feature
